- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
  # Copy Project Files
  - name: copy project files to ec2 
    copy:
      src: /root/project/.circleci/ansible/run_pod.sh
      dest: /home/ubuntu/
      force : yes

  - name: make run_pod.sh executable by changing permissions 
    file: dest=/home/ubuntu/run_pod.sh mode=a+x

  - name: Running pod using script
    shell: sudo /home/ubuntu/run_pod.sh
    
        


