Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    WebAppServersMinSize:
        Description: Minimum  Instances Number for Autoscaling Group
        Type: String
        Default: '1'
    WebAppServersMaxSize:
        Description: Maximum Instances Number for Autoscaling Group
        Type: String
        Default: '4'
    ID:
    Description: Unique identifier.
    Type: String
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub capstone-${ID}
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
          sudo service docker start
          sudo apt-get install python3 -y
          sudo apt-get install python3-pip
          alternatives --set python /user/bin/python3
          sudo curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
          sudo chmod +x ./kubectl
          sudo mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          sudo kubectl version --short --client
#          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
#          chmod +x minikube 
#          sudo mv minikube /usr/local/bin/
#          minikube start
          
      ImageId: ami-07b4f3c02c7f83d59
      KeyName: udacity
      SecurityGroups:
       - Ref: WebServerSecurityGroup
      InstanceType: t2.micro
      BlockDeviceMappings:
       - DeviceName: "/dev/sdk"
         Ebs:
           VolumeSize: '20'
  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: 
          !Sub "${EnvironmentName}-PUB-NETS"
      LaunchConfigurationName:
        Ref: WebAppLaunchConfig
      MinSize: !Ref WebAppServersMinSize
      MaxSize: !Ref WebAppServersMaxSize
      TargetGroupARNs:
      - Ref: WebAppTargetGroup        
  WebAppTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        HealthCheckIntervalSeconds: 20
        HealthCheckPath: /
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 10
        HealthyThresholdCount: 2
        Port: 80
        Protocol: HTTP
        UnhealthyThresholdCount: 5
        VpcId: 
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-VPCID" 